name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:     # Manual trigger
  push:
    branches:
      - main             # Trigger on main branch push

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/snake-crimson.svg?color_snake=#dc143c&color_dots=#ffeaea,#ffb3b3,#ff6666,#ff3333,#cc0000
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            dist/snake-crimson-dark.svg?palette=github-dark&color_snake=#dc143c&color_dots=#ffdddd,#ffaaaa,#ff6666,#ff3333,#cc0000
            dist/snake-crimson-beautiful.svg?color_snake=#dc143c&color_dots=#161B22,#b22222,#cc3030,#dc143c,#8b0000&background=161B22
            dist/snake-custom-crimson.svg?color_snake=#dc143c&color_dots=#161b22,#4d0d0d,#801515,#b22222,#dc143c&background=161b22
            dist/snake-green-dots-red-snake.svg?color_snake=#dc143c&color_dots=#161b22,#01311f,#034525,#0f6d31,#00c647&background=161b22
            dist/snake-lightgreen.svg?color_snake=#cc0000&color_dots=#EBEDF0,#a3f7bf,#38c172,#1f8b4c,#114b29,&background=EBEDF0
            

  


        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}  # <- Use PAT here
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
